version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_ROOT_PASSWORD=Srhiulli@@@>>>1982
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=Srhiulli@@@>>>1982
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Srhiulli@@@>>>1982
      - OPENSEARCH_HOSTS=https://opensearch:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600
    networks:
      - opensearch-net

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    depends_on:
      - opensearch
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=https://opensearch:9200
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=Srhiulli@@@>>>1982
      - OPENSEARCH_SSL_VERIFICATIONMODE=none
    networks:
      - opensearch-net

volumes:
  opensearch-data:

networks:
  opensearch-net:
    driver: bridge